export const PortfolioData = [
    {
        id: 1,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 2,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 3,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
    {
        id: 5,
        image: "img/portfolio/16.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 7,
        image: "img/portfolio/17.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 8,
        image: "img/portfolio/17.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 9,
        image: "img/portfolio/17.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
    {
        id: 11,
        image: "img/portfolio/18.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 12,
        image: "img/portfolio/18.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 13,
        image: "img/portfolio/18.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
    {
        id: 15,
        image: "img/portfolio/19.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 16,
        image: "img/portfolio/19.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 17,
        image: "img/portfolio/19.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 19,
        image: "img/portfolio/20.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 20,
        image: "img/portfolio/20.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 21,
        image: "img/portfolio/20.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 23,
        image: "img/portfolio/21.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 24,
        image: "img/portfolio/21.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 25,
        image: "img/portfolio/21.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },

    {
        id: 27,
        image: "img/portfolio/22.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "website",
    },
    {
        id: 28,
        image: "img/portfolio/22.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 29,
        image: "img/portfolio/22.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 31,
        image: "img/portfolio/23.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 32,
        image: "img/portfolio/23.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 33,
        image: "img/portfolio/23.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "website",
    },

    {
        id: 35,
        image: "img/portfolio/24.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },
    {
        id: 36,
        image: "img/portfolio/24.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 37,
        image: "img/portfolio/24.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 39,
        image: "img/portfolio/25.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 40,
        image: "img/portfolio/25.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 41,
        image: "img/portfolio/25.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },

    {
        id: 43,
        image: "img/portfolio/26.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 44,
        image: "img/portfolio/26.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 45,
        image: "img/portfolio/26.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "consultancy",
    },

    {
        id: 47,
        image: "img/portfolio/27.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "graphics",
    },
    {
        id: 48,
        image: "img/portfolio/27.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "all",
    },
    {
        id: 49,
        image: "img/portfolio/27.jpg",
        subTitle1: "App",
        subTitle2: "Design",
        title: "Spay Mobile Banking App",
        category: "ui-ux",
    },
];
